apiVersion: v1
kind: Service
metadata:
  name: codebuddy
spec:
  selector:
    app: codebuddy
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: gateway
    port: 3001
    targetPort: 3001
  type: ClusterIP
