/**
 * Cloud Deployment Configuration Generator
 *
 * Generates deployment configs for popular cloud platforms.
 * Advanced enterprise architecture for multi-platform deployment support.
 *
 * Supported platforms: Fly.io, Railway, Render, Hetzner, Northflank, GCP
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { logger } from '../utils/logger.js';

function sanitizeAppName(name: string): string {
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(name)) {
    throw new Error(
      `Invalid app name "${name}". Only alphanumeric characters, hyphens, and underscores are allowed.`
    );
  }
  return name;
}

function sanitizeEnvValue(value: string): string {
  // Escape characters dangerous in YAML/TOML string contexts and shell
  return value.replace(/[\\"$`!]/g, '\\$&');
}

// ============================================================================
// Types
// ============================================================================

export type CloudPlatform = 'fly' | 'railway' | 'render' | 'hetzner' | 'northflank' | 'gcp';

export interface DeployConfig {
  platform: CloudPlatform;
  appName: string;
  region?: string;
  port?: number;
  env?: Record<string, string>;
  memory?: string;
  cpus?: number;
}

export interface GenerateResult {
  success: boolean;
  files: Array<{ path: string; content: string }>;
  instructions: string;
}

// ============================================================================
// Config Generators
// ============================================================================

export function generateFlyConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);
  const port = config.port || 3000;
  const region = config.region || 'iad';

  const flyToml = `# Generated by Code Buddy
app = "${appName}"
primary_region = "${region}"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = ${port}
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[env]
  NODE_ENV = "production"
  PORT = "${port}"
${Object.entries(config.env || {}).map(([k, v]) => `  ${k} = "${sanitizeEnvValue(v)}"`).join('\n')}

[[vm]]
  memory = "${config.memory || '512mb'}"
  cpus = ${config.cpus || 1}
`;

  return {
    success: true,
    files: [{ path: 'fly.toml', content: flyToml }],
    instructions: `Deploy with: fly launch --name ${appName} --region ${region}`,
  };
}

export function generateRailwayConfig(_config: DeployConfig): GenerateResult {
  const railwayJson = JSON.stringify({
    $schema: 'https://railway.app/railway.schema.json',
    build: { builder: 'DOCKERFILE', dockerfilePath: 'Dockerfile' },
    deploy: {
      startCommand: 'node dist/index.js daemon start --foreground',
      healthcheckPath: '/api/health',
      restartPolicyType: 'ON_FAILURE',
      restartPolicyMaxRetries: 3,
    },
  }, null, 2);

  return {
    success: true,
    files: [{ path: 'railway.json', content: railwayJson }],
    instructions: `Deploy with: railway up`,
  };
}

export function generateRenderConfig(config: DeployConfig): GenerateResult {
  const port = config.port || 3000;
  const renderYaml = `# Generated by Code Buddy
services:
  - type: web
    name: ${sanitizeAppName(config.appName)}
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "${port}"
${Object.entries(config.env || {}).map(([k, v]) => `      - key: ${k}\n        value: "${sanitizeEnvValue(v)}"`).join('\n')}
`;

  return {
    success: true,
    files: [{ path: 'render.yaml', content: renderYaml }],
    instructions: `Connect your repo on render.com and it will auto-deploy.`,
  };
}

export function generateHetznerConfig(config: DeployConfig): GenerateResult {
  const appName = sanitizeAppName(config.appName);
  const cloudInit = `#cloud-config
# Generated by Code Buddy — Hetzner Cloud Init
package_update: true
packages:
  - docker.io
  - docker-compose
  - git

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - git clone https://github.com/your-org/${appName}.git /opt/${appName}
  - cd /opt/${appName} && docker compose up -d
`;

  return {
    success: true,
    files: [{ path: 'hetzner-cloud-init.yml', content: cloudInit }],
    instructions: `Create a Hetzner server with this cloud-init script as user data.`,
  };
}

export function generateNorthflankConfig(config: DeployConfig): GenerateResult {
  const nfJson = JSON.stringify({
    name: sanitizeAppName(config.appName),
    description: 'Code Buddy AI assistant',
    type: 'combined',
    services: [{
      name: 'gateway',
      type: 'deployment',
      billing: { deploymentPlan: 'nf-compute-20' },
      buildpack: { builder: 'dockerfile', dockerfilePath: '/Dockerfile' },
      ports: [{ name: 'http', internalPort: config.port || 3000, protocol: 'HTTP' }],
      healthChecks: [{ type: 'http', path: '/api/health', port: config.port || 3000 }],
    }],
  }, null, 2);

  return {
    success: true,
    files: [{ path: 'northflank.json', content: nfJson }],
    instructions: `Import this template in Northflank dashboard.`,
  };
}

export function generateGCPConfig(config: DeployConfig): GenerateResult {
  const port = config.port || 3000;
  const region = config.region || 'us-central1';

  const appYaml = `# Generated by Code Buddy — Google Cloud Run
runtime: custom
env: flex

service: ${sanitizeAppName(config.appName)}

env_variables:
  NODE_ENV: production
  PORT: "${port}"
${Object.entries(config.env || {}).map(([k, v]) => `  ${k}: "${sanitizeEnvValue(v)}"`).join('\n')}

resources:
  cpu: ${config.cpus || 1}
  memory_gb: ${config.memory ? parseFloat(config.memory) / 1024 : 0.5}

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 1
`;

  return {
    success: true,
    files: [{ path: 'app.yaml', content: appYaml }],
    instructions: `Deploy with: gcloud app deploy --region=${region}`,
  };
}

// ============================================================================
// Main Generator
// ============================================================================

export function generateDeployConfig(config: DeployConfig): GenerateResult {
  switch (config.platform) {
    case 'fly': return generateFlyConfig(config);
    case 'railway': return generateRailwayConfig(config);
    case 'render': return generateRenderConfig(config);
    case 'hetzner': return generateHetznerConfig(config);
    case 'northflank': return generateNorthflankConfig(config);
    case 'gcp': return generateGCPConfig(config);
    default:
      return { success: false, files: [], instructions: `Unknown platform: ${config.platform}` };
  }
}

export async function writeDeployConfigs(
  outputDir: string,
  config: DeployConfig
): Promise<GenerateResult> {
  const result = generateDeployConfig(config);
  if (!result.success) return result;

  for (const file of result.files) {
    const fullPath = path.join(outputDir, file.path);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, file.content, 'utf8');
    logger.info(`Wrote ${fullPath}`);
  }

  return result;
}
